/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ShippingBoxStated.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ShippingBoxStated.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 0.04]}>
          <primitive object={nodes.Body} />
          <skinnedMesh name="backSide" geometry={nodes.backSide.geometry} material={materials.Material} skeleton={nodes.backSide.skeleton}>
            <skinnedMesh name="backSideCover" geometry={nodes.backSideCover.geometry} material={materials['Material.004']} skeleton={nodes.backSideCover.skeleton} />
          </skinnedMesh>
          <skinnedMesh name="bottomSide" geometry={nodes.bottomSide.geometry} material={materials.Material} skeleton={nodes.bottomSide.skeleton}>
            <skinnedMesh name="bottomSideCover" geometry={nodes.bottomSideCover.geometry} material={materials['Material.005']} skeleton={nodes.bottomSideCover.skeleton} />
          </skinnedMesh>
          <skinnedMesh name="Flapes" geometry={nodes.Flapes.geometry} material={materials.Material} skeleton={nodes.Flapes.skeleton} />
          <skinnedMesh name="frontFace" geometry={nodes.frontFace.geometry} material={materials.Material} skeleton={nodes.frontFace.skeleton}>
            <skinnedMesh name="frontCover" geometry={nodes.frontCover.geometry} material={materials.img} skeleton={nodes.frontCover.skeleton} />
          </skinnedMesh>
          <skinnedMesh name="frontFlap" geometry={nodes.frontFlap.geometry} material={materials.Material} skeleton={nodes.frontFlap.skeleton} />
          <skinnedMesh name="leftSide" geometry={nodes.leftSide.geometry} material={materials.Material} skeleton={nodes.leftSide.skeleton}>
            <skinnedMesh name="leftSideCover" geometry={nodes.leftSideCover.geometry} material={materials['Material.002']} skeleton={nodes.leftSideCover.skeleton} />
          </skinnedMesh>
          <skinnedMesh name="rightSide" geometry={nodes.rightSide.geometry} material={materials.Material} skeleton={nodes.rightSide.skeleton}>
            <skinnedMesh name="rightSideCover" geometry={nodes.rightSideCover.geometry} material={materials['Material.003']} skeleton={nodes.rightSideCover.skeleton} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ShippingBoxStated.glb')
